const BadgesList = {
  HTML: {
    name: "HTML",
    width: "118.25px",
    height: "43px",
    src: "https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white",
  },
  CSS: {
    name: "CSS",
    width: "107px",
    height: "43px",
    src: "https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white",
  },
  JS: {
    name: "JS",
    width: "156.5px",
    height: "43px",
    src: "https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E",
  },
  TS: {
    name: "TS",
    width: "156.5px",
    height: "43px",
    src: "https://img.shields.io/badge/typescript-%23007ACC.svg?style=for-the-badge&logo=typescript&logoColor=white",
  },
  SOCKETIO: {
    name: "SOCKETIO",
    width: "146.25px",
    height: "43px",
    src: "https://img.shields.io/badge/Socket.io-black?style=for-the-badge&logo=socket.io&badgeColor=010101",
  },
  NODEJS: {
    name: "NODEJS",
    width: "130.73px",
    height: "43px",
    src: "https://img.shields.io/badge/node.js-6DA55F?style=for-the-badge&logo=node.js&logoColor=white",
  },
  MARIADB: {
    name: "MARIADB",
    width: "136.75px",
    height: "43px",
    src: "https://img.shields.io/badge/MariaDB-003545?style=for-the-badge&logo=mariadb&logoColor=white",
  },
  WORDPRESS: {
    name: "WORDPRESS",
    width: "157.25px",
    height: "43px",
    src: "https://img.shields.io/badge/WordPress-%23117AC9.svg?style=for-the-badge&logo=WordPress&logoColor=white",
  },
  BOOTSTRAP: {
    name: "BOOTSTRAP",
    width: "153.25px",
    height: "43px",
    src: "https://img.shields.io/badge/bootstrap-%23563D7C.svg?style=for-the-badge&logo=bootstrap&logoColor=white",
  },
  REACTJS: {
    name: "REACTJS",
    width: "116.25px",
    height: "43px",
    src: "https://img.shields.io/badge/react-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB",
  },
  VITE: {
    name: "VITE",
    width: "105px",
    height: "43px",
    src: "https://img.shields.io/badge/vite-%23646CFF.svg?style=for-the-badge&logo=vite&logoColor=white",
  },
  NGINX: {
    name: "NGINX",
    width: "118.25px",
    height: "43px",
    src: "https://img.shields.io/badge/nginx-%23009639.svg?style=for-the-badge&logo=nginx&logoColor=white",
  },
  KUBERNETES: {
    name: "KUBERNETES",
    width: "160.5px",
    height: "43px",
    src: "https://img.shields.io/badge/kubernetes-%23326ce5.svg?style=for-the-badge&logo=kubernetes&logoColor=white",
  },
  GO: {
    name: "GO",
    width: "92.5px",
    height: "43px",
    src: "https://img.shields.io/badge/go-%2300ADD8.svg?style=for-the-badge&logo=go&logoColor=white",
  },
  RUST: {
    name: "RUST",
    width: "108px",
    height: "43px",
    src: "https://img.shields.io/badge/rust-%23000000.svg?style=for-the-badge&logo=rust&logoColor=white",
  },
  PYTHON: {
    name: "PYTHON",
    width: "127.5px",
    height: "43px",
    src: "https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54",
  },
  TENSORFLOW: {
    name: "TENSORFLOW",
    width: "164.5px",
    height: "43px",
    src: "https://img.shields.io/badge/TensorFlow-%23FF6F00.svg?style=for-the-badge&logo=TensorFlow&logoColor=white",
  },
  SHELL: {
    name: "SHELL",
    width: "169px",
    height: "43px",
    src: "https://img.shields.io/badge/shell_script-%23121011.svg?style=for-the-badge&logo=gnu-bash&logoColor=white",
  },
  ALPINE: {
    name: "ALPINE",
    width: "170px",
    height: "43px",
    src: "https://img.shields.io/badge/Alpine_Linux-%230D597F.svg?style=for-the-badge&logo=alpine-linux&logoColor=white",
  },
  DOCKER: {
    name: "DOCKER",
    width: "127.5px",
    height: "43px",
    src: "https://img.shields.io/badge/docker-%230db7ed.svg?style=for-the-badge&logo=docker&logoColor=white",
  },
  REACTNATIVE: {
    name: "REACTNATIVE",
    width: "171px",
    height: "43px",
    src: "https://img.shields.io/badge/react_native-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB",
  },
  UBUNTU: {
    name: "UBUNTU",
    width: "128.5px",
    height: "43px",
    src: "https://img.shields.io/badge/ubuntu-E95420?style=for-the-badge&logo=ubuntu&logoColor=white",
  },
  LINUX: {
    name: "LINUX",
    width: "116.25px",
    height: "43px",
    src: "https://img.shields.io/badge/Linux-FCC624?style=for-the-badge&logo=linux&logoColor=black",
  },
  LINODE: {
    name: "LINODE",
    width: "104.5px",
    height: "43px",
    src: "https://img.shields.io/badge/linode-%2300A95C.svg?style=for-the-badge&logo=linode&logoColor=white",
  },
  CLOUDFLARE: {
    name: "CLOUDFLARE",
    width: "159.5px",
    height: "43px",
    src: "https://img.shields.io/badge/Cloudflare-F38020?style=for-the-badge&logo=cloudflare&logoColor=white",
  },
  GITHUBACTIONS: {
    name: "GITHUBACTIONS",
    width: "190.5px",
    height: "43px",
    src: "https://img.shields.io/badge/GitHub_Actions-2088FF?style=for-the-badge&logo=github-actions&logoColor=white",
  },
  GITHUB: {
    name: "GITHUB",
    width: "125.5px",
    height: "43px",
    src: "https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white",
  },
  GIT: {
    name: "GIT",
    width: "97.75px",
    height: "43px",
    src: "https://img.shields.io/badge/git-%23F05033.svg?style=for-the-badge&logo=git&logoColor=white",
  },
  MARKDOWN: {
    name: "MARKDOWN",
    width: "153px",
    height: "43px",
    src: "https://img.shields.io/badge/markdown-%23000000.svg?style=for-the-badge&logo=markdown&logoColor=white",
  },
  JEST: {
    name: "JEST",
    width: "105px",
    height: "43px",
    src: "https://img.shields.io/badge/jest-%23C21325.svg?style=for-the-badge&logo=jest&logoColor=white",
  },
  ESLINT: {
    name: "ESLINT",
    width: "122.5px",
    height: "43px",
    src: "https://img.shields.io/badge/eslint-%234B32C3.svg?style=for-the-badge&logo=eslint&logoColor=white",
  },
};

export default BadgesList;